version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: analytics-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: analytics
      MYSQL_USER: analytics
      MYSQL_PASSWORD: analytics
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: analytics-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      DATABASE_URL: mysql://analytics:analytics@mysql:3306/analytics
      PORT: 3000
      LOG_LEVEL: info
    ports:
      - '3000:3000'
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_data:
    driver: local
